// Copyright 2026 Gravity Labs
// SPDX-License-Identifier: Apache-2.0
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import { findAdb, parseProperties, resolveProjectRoot, resolveSdkDir } from "./adb.js";

// Wraps the real readFileSync in a spy rather than replacing it: every
// existing GRA-87 test still gets real file contents back, but GRA-119's
// AC2 test can assert the call never happened at all — not just that the
// right value came back, which a backwards precedence that read the file
// anyway and then discarded it would also produce.
vi.mock("node:fs", async (importOriginal) => {
  const actual = await importOriginal<typeof import("node:fs")>();
  return { ...actual, readFileSync: vi.fn(actual.readFileSync) };
});

/**
 * Finding adb is not interesting until it fails, and the way it failed was
 * this: the MCP server read only ANDROID_HOME and ANDROID_SDK_ROOT, neither of
 * which a stock Android Studio install sets, while the Gradle plugin read
 * sdk.dir out of local.properties and found the SDK every time. The same
 * machine, the same SDK, and two Porthole commands disagreeing about whether
 * it existed.
 *
 * So these tests are mostly about order and about the file format, and they
 * use real directories in a real temporary tree rather than a mocked fs —
 * existsSync against a path that was never created is the bug, not the
 * assertion, and a fake filesystem would have happily agreed with either.
 */

const BINARY = process.platform === "win32" ? "adb.exe" : "adb";

let roots: string[] = [];
let savedEnvironment: Record<string, string | undefined> = {};

function temporaryDirectory(): string {
  const directory = mkdtempSync(path.join(tmpdir(), "porthole-adb-"));
  roots.push(directory);
  return directory;
}

/** An SDK as far as findAdb is concerned: platform-tools with adb in it. */
function fakeSdk(): string {
  const sdk = temporaryDirectory();
  mkdirSync(path.join(sdk, "platform-tools"));
  writeFileSync(path.join(sdk, "platform-tools", BINARY), "");
  return sdk;
}

/** A path as Android Studio would write it into local.properties. */
function javaEscaped(value: string): string {
  return value.replace(/\\/g, "\\\\").replace(/:/g, "\\:");
}

function writeLocalProperties(directory: string, contents: string): void {
  writeFileSync(path.join(directory, "local.properties"), contents);
}

function workingDirectory(directory: string): void {
  vi.spyOn(process, "cwd").mockReturnValue(directory);
}

beforeEach(() => {
  savedEnvironment = {
    ANDROID_HOME: process.env.ANDROID_HOME,
    ANDROID_SDK_ROOT: process.env.ANDROID_SDK_ROOT,
    PORTHOLE_SDK_DIR: process.env.PORTHOLE_SDK_DIR,
    PORTHOLE_PROJECT_ROOT: process.env.PORTHOLE_PROJECT_ROOT,
  };
  // This machine has neither set, which is the case worth defaulting to; a
  // machine that does must not change what these tests mean.
  delete process.env.ANDROID_HOME;
  delete process.env.ANDROID_SDK_ROOT;
  delete process.env.PORTHOLE_SDK_DIR;
  delete process.env.PORTHOLE_PROJECT_ROOT;
  vi.mocked(readFileSync).mockClear();
});

afterEach(() => {
  // Not restoreAllMocks(): the readFileSync mock above is a vi.fn() wrapping
  // the real implementation, not a vi.spyOn, and mockRestore on one of those
  // degrades it to a bare mock with no implementation at all — which would
  // silently break every later test's local.properties reads. clearAllMocks
  // resets call history (what every test here actually depends on) without
  // touching implementations, which is all any test needs: every findAdb
  // test rearms process.cwd's mock return value itself via workingDirectory.
  vi.clearAllMocks();
  for (const [name, value] of Object.entries(savedEnvironment)) {
    if (value === undefined) delete process.env[name];
    else process.env[name] = value;
  }
  for (const root of roots) rmSync(root, { recursive: true, force: true });
  roots = [];
});

describe("parseProperties", () => {
  it("unescapes the Windows path Android Studio writes", () => {
    const properties = parseProperties(
      String.raw`sdk.dir=C\:\\Users\\james\\AppData\\Local\\Android\\Sdk`,
    );
    expect(properties.get("sdk.dir")).toBe("C:\\Users\\james\\AppData\\Local\\Android\\Sdk");
  });

  it("reads a file with CRLF line endings and comments around the value", () => {
    const text = [
      "## This file is automatically generated by Android Studio.",
      "# Location of the SDK. This is only used by Gradle.",
      String.raw`sdk.dir=C\:\\Users\\james\\AppData\\Local\\Android\\Sdk`,
      "! and a trailing comment, which is not part of anything",
      "",
    ].join("\r\n");
    expect(parseProperties(text).get("sdk.dir")).toBe(
      "C:\\Users\\james\\AppData\\Local\\Android\\Sdk",
    );
  });

  it("takes a colon or bare whitespace as the separator, as Java does", () => {
    expect(parseProperties("sdk.dir:/opt/sdk").get("sdk.dir")).toBe("/opt/sdk");
    expect(parseProperties("sdk.dir /opt/sdk").get("sdk.dir")).toBe("/opt/sdk");
    expect(parseProperties("  sdk.dir = /opt/sdk  ").get("sdk.dir")).toBe("/opt/sdk  ");
  });

  it("joins a value continued over two lines", () => {
    expect(parseProperties("sdk.dir=/opt/\\\n  android-sdk").get("sdk.dir")).toBe(
      "/opt/android-sdk",
    );
  });

  it("keeps a # inside a value, which Java does not treat as a comment", () => {
    expect(parseProperties("sdk.dir=/opt/sdk#1").get("sdk.dir")).toBe("/opt/sdk#1");
  });

  it("finds nothing in a file that declares nothing", () => {
    expect(parseProperties("# just a comment\n\nflutter.sdk=/opt/flutter\n").has("sdk.dir")).toBe(
      false,
    );
  });
});

describe("findAdb", () => {
  it("finds adb through sdk.dir with no environment variables set", () => {
    const sdk = fakeSdk();
    const project = temporaryDirectory();
    writeLocalProperties(project, `sdk.dir=${javaEscaped(sdk)}\n`);
    workingDirectory(project);

    expect(findAdb()).toBe(path.join(sdk, "platform-tools", BINARY));
  });

  it("prefers local.properties over the environment, as the Gradle plugin does", () => {
    const declared = fakeSdk();
    const environment = fakeSdk();
    const project = temporaryDirectory();
    writeLocalProperties(project, `sdk.dir=${javaEscaped(declared)}\n`);
    workingDirectory(project);
    process.env.ANDROID_HOME = environment;
    process.env.ANDROID_SDK_ROOT = environment;

    // Swapping the order in sdkRoot() fails here, which is the point: the
    // plugin reads local.properties first and the two must not diverge again.
    expect(findAdb()).toBe(path.join(declared, "platform-tools", BINARY));
    expect(findAdb()).not.toBe(path.join(environment, "platform-tools", BINARY));
  });

  it("falls back to the environment when no local.properties declares sdk.dir", () => {
    const sdk = fakeSdk();
    const project = temporaryDirectory();
    writeLocalProperties(project, "# an SDK is not mentioned here\nflutter.sdk=/opt/flutter\n");
    workingDirectory(project);
    process.env.ANDROID_HOME = sdk;

    expect(findAdb()).toBe(path.join(sdk, "platform-tools", BINARY));
  });

  it("skips an environment variable pointing nowhere and tries the next", () => {
    const sdk = fakeSdk();
    workingDirectory(temporaryDirectory());
    process.env.ANDROID_HOME = path.join(sdk, "does-not-exist");
    process.env.ANDROID_SDK_ROOT = sdk;

    expect(findAdb()).toBe(path.join(sdk, "platform-tools", BINARY));
  });

  it("leaves adb to the PATH when sdk.dir has no platform-tools under it", () => {
    // The plugin stops at sdk.dir too: a declared SDK is the answer even when
    // adb is not in it. Quietly reaching for a different SDK is how the two
    // sides came to disagree in the first place.
    const empty = temporaryDirectory();
    const project = temporaryDirectory();
    writeLocalProperties(project, `sdk.dir=${javaEscaped(empty)}\n`);
    workingDirectory(project);
    process.env.ANDROID_HOME = fakeSdk();

    expect(findAdb()).toBe(BINARY);
  });

  it("leaves adb to the PATH when there is nothing to find", () => {
    workingDirectory(temporaryDirectory());
    expect(findAdb()).toBe(BINARY);
  });

  it("walks up to the build root from a module inside it", () => {
    const sdk = fakeSdk();
    const project = temporaryDirectory();
    writeLocalProperties(project, `sdk.dir=${javaEscaped(sdk)}\n`);
    const deep = path.join(project, "a", "b", "c", "d", "e");
    mkdirSync(deep, { recursive: true });
    workingDirectory(deep);

    expect(findAdb()).toBe(path.join(sdk, "platform-tools", BINARY));
  });

  it("gives up rather than climbing the whole disk", () => {
    const sdk = fakeSdk();
    const project = temporaryDirectory();
    writeLocalProperties(project, `sdk.dir=${javaEscaped(sdk)}\n`);
    const deeper = path.join(project, "a", "b", "c", "d", "e", "f");
    mkdirSync(deeper, { recursive: true });
    workingDirectory(deeper);

    expect(findAdb()).toBe(BINARY);
  });

  it("passes a local.properties that says nothing on its way up", () => {
    const sdk = fakeSdk();
    const project = temporaryDirectory();
    writeLocalProperties(project, `sdk.dir=${javaEscaped(sdk)}\n`);
    const appModule = path.join(project, "app");
    mkdirSync(appModule);
    writeLocalProperties(appModule, "# nothing about an SDK here\n");
    workingDirectory(appModule);

    expect(findAdb()).toBe(path.join(sdk, "platform-tools", BINARY));
  });

  it("terminates at the root of the filesystem", () => {
    workingDirectory(path.parse(path.resolve(tmpdir())).root);
    // The walk stops because a root is its own parent; without that it spins
    // on "/" or "C:\" forever, which is a hang rather than a wrong answer.
    expect(typeof findAdb()).toBe("string");
  });
});

/**
 * GRA-119: `.mcp.json`, generated by `PortholeMcpConfigTask`, now carries
 * `PORTHOLE_PROJECT_ROOT` and `PORTHOLE_SDK_DIR` — values the plugin knows
 * with certainty at configure time, rather than the `process.cwd()`
 * inference GRA-87's fix rested on. These tests pin the precedence stated in
 * resolveSdkDir's doc comment (PORTHOLE_SDK_DIR, then GRA-87's walk, then the
 * environment, then PATH) and prove the interesting half of it: that an
 * explicit PORTHOLE_SDK_DIR short-circuits before local.properties is ever
 * read, not merely that it wins in the end.
 */
describe("resolveSdkDir", () => {
  it("prefers PORTHOLE_SDK_DIR over local.properties, without reading local.properties at all", () => {
    const declaredViaEnv = fakeSdk();
    // Sitting exactly where the walk would look, and pointing somewhere
    // else: if precedence were backwards, or if the code read this file
    // before checking the environment and only discarded it afterwards,
    // either mistake shows up here.
    const poisoned = fakeSdk();
    const project = temporaryDirectory();
    writeLocalProperties(project, `sdk.dir=${javaEscaped(poisoned)}\n`);
    workingDirectory(project);
    process.env.PORTHOLE_SDK_DIR = declaredViaEnv;

    expect(resolveSdkDir()).toEqual({ directory: declaredViaEnv, source: "PORTHOLE_SDK_DIR" });
    expect(findAdb()).toBe(path.join(declaredViaEnv, "platform-tools", BINARY));
    expect(readFileSync).not.toHaveBeenCalled();
  });

  it("prefers PORTHOLE_SDK_DIR over the environment too", () => {
    const declaredViaEnv = fakeSdk();
    const fromAndroidHome = fakeSdk();
    workingDirectory(temporaryDirectory());
    process.env.PORTHOLE_SDK_DIR = declaredViaEnv;
    process.env.ANDROID_HOME = fromAndroidHome;

    expect(resolveSdkDir()).toEqual({ directory: declaredViaEnv, source: "PORTHOLE_SDK_DIR" });
  });

  it("falls back to GRA-87's walk when PORTHOLE_SDK_DIR is unset — AC3", () => {
    const sdk = fakeSdk();
    const project = temporaryDirectory();
    writeLocalProperties(project, `sdk.dir=${javaEscaped(sdk)}\n`);
    workingDirectory(project);

    expect(resolveSdkDir()).toEqual({ directory: sdk, source: "local.properties" });
    expect(readFileSync).toHaveBeenCalled();
  });

  it("falls back to ANDROID_HOME, then ANDROID_SDK_ROOT, in that order", () => {
    workingDirectory(temporaryDirectory());
    const fromHome = fakeSdk();
    process.env.ANDROID_HOME = fromHome;
    process.env.ANDROID_SDK_ROOT = fakeSdk();
    expect(resolveSdkDir()).toEqual({ directory: fromHome, source: "ANDROID_HOME" });

    delete process.env.ANDROID_HOME;
    const fromRoot = fakeSdk();
    process.env.ANDROID_SDK_ROOT = fromRoot;
    expect(resolveSdkDir()).toEqual({ directory: fromRoot, source: "ANDROID_SDK_ROOT" });
  });

  it("reports PATH with a null directory when nothing resolves — the seam porthole_status reports through", () => {
    workingDirectory(temporaryDirectory());
    expect(resolveSdkDir()).toEqual({ directory: null, source: "PATH" });
  });

  it("empty PORTHOLE_SDK_DIR is treated as unset, not as an empty-string SDK", () => {
    const sdk = fakeSdk();
    const project = temporaryDirectory();
    writeLocalProperties(project, `sdk.dir=${javaEscaped(sdk)}\n`);
    workingDirectory(project);
    process.env.PORTHOLE_SDK_DIR = "   ";

    expect(resolveSdkDir()).toEqual({ directory: sdk, source: "local.properties" });
  });

  it("finds adb via PORTHOLE_SDK_DIR from a directory that is not the project root at all — AC4", () => {
    // The scenario the whole ticket is about: the server was not launched
    // from the workspace root GRA-87's walk assumed. Without
    // PORTHOLE_SDK_DIR this would land findAdb on bare "adb.exe"/"adb",
    // because nothing above an unrelated cwd names an SDK.
    const sdk = fakeSdk();
    const elsewhere = temporaryDirectory();
    workingDirectory(elsewhere);
    process.env.PORTHOLE_SDK_DIR = sdk;

    expect(findAdb()).toBe(path.join(sdk, "platform-tools", BINARY));
  });
});

describe("resolveProjectRoot", () => {
  it("uses PORTHOLE_PROJECT_ROOT when the generated config set it", () => {
    const root = temporaryDirectory();
    workingDirectory(temporaryDirectory()); // a different directory than root
    process.env.PORTHOLE_PROJECT_ROOT = root;

    expect(resolveProjectRoot()).toEqual({ directory: root, source: "PORTHOLE_PROJECT_ROOT" });
  });

  it("falls back to process.cwd() when unset, which is what GRA-87 already assumed", () => {
    const cwd = temporaryDirectory();
    workingDirectory(cwd);

    expect(resolveProjectRoot()).toEqual({ directory: cwd, source: "cwd" });
  });

  it("resolveSdkDir's local.properties walk starts from PORTHOLE_PROJECT_ROOT, not cwd — AC4 again, end to end", () => {
    const sdk = fakeSdk();
    const project = temporaryDirectory();
    writeLocalProperties(project, `sdk.dir=${javaEscaped(sdk)}\n`);
    // The server's actual cwd is somewhere with no local.properties at all —
    // the case that used to leave GRA-87's walk with nothing to find.
    workingDirectory(temporaryDirectory());
    process.env.PORTHOLE_PROJECT_ROOT = project;

    expect(resolveSdkDir()).toEqual({ directory: sdk, source: "local.properties" });
    expect(findAdb()).toBe(path.join(sdk, "platform-tools", BINARY));
  });
});
